
<div class="channelize-setup-instruction">
    <h2>Setup Instructions</h2>
    <ul>
        <li>
            <p><b>1.</b> After installing the Live Shopping & Video Streams successfully, the next step is to configure the extension's General settings.</p>
        </li>
        <li>
            <p><b>2.</b> To do so, sign up for a <a href="https://channelize.io/lsc/account/login" target="_blank">Channelize.io account</a>, choose a subscription plan, and complete the sign-up process.</p>
        </li>
        <li>
            <p><b>3.</b> You will then be redirected to your <b>Live Shopping &amp; Video Streams Dashboard</b>, also known as the <b>Production Dashboard</b>.</p>
        </li>
        <li>
            <p><b>4.</b> Now go to your dashboard's <b>Help &amp; Support</b> page, where you can see your Public &amp; Private Keys as well as other account information.</p>
            <p class="instruction">Copy and paste these keys into the extension's <b>General settings</b> and save the changes.</p>
        </li>
        <li>
            
        </li>
        <li>
            <p><b>5.</b> Once this is completed, the extension has been successfully configured. You can find your <b>Live Shop Page URL</b> in the extension's <b>Live Shop Page</b>.</p>
            <p class="instruction">This page is also available in <b>Pages</b> with title <b>Streams</b>. If you want to learn more about this, go to our <a href="<?=$block->getUrl('liveshopping/instruction/page')?>">Live Shop Page</a>.</p>
        </li>
        <li>
            <p><b>6.</b> You are now ready to create Shopping Shows in your production dashboard and go Live from broadcaster apps. To learn more, visit our <a href="http://help.channelize.io/67--getting-started-with-live-video-shopping--streams-dashboard" target="_blank">Help Center</a>.</p>
            <p class="instruction">Please remember to include the <b>Product ID</b> of each product when adding products to your Live Shopping Show for <b>Cart Integration</b>.</p>
            <p class="instruction">To get Product ID, navigate to <b>Magento Admin Panel > Catalog > Products</b>. You will see the list of all the products existing in your store. Now, you need to copy the Product's ID as <a href="https://prnt.sc/1wkscjp" target="_blank">shown here</a>, paste it into your production dashboard as <a href="https://prnt.sc/1wpo1fp" target="_blank">shown here</a> & save the changes.</p>
        </li>
        
        <li>
            <p><b>Note:</b> Our Extension is compatible with Magento version 2.0 and higher.</p>
        </li>
    </ul>
</div>

<style>
    .channelize-setup-instruction h1, h2, h3 {
        font-weight: 600;
    }
    .channelize-setup-instruction ul {
        list-style-type: none;
    }
    .channelize-setup-instruction p {
        padding: 3px 0px;
    }
    .channelize-setup-instruction p.instruction {
        margin-left: 15px;
    }
</style>